In [59]:
import numpy as np
#matrix can be thought as the set of vectors
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [60]:
Q = np.array([[1,1],[1,-1],[1,0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [61]:
C1 = np.add(P,Q)
C2 = np.subtract(P,Q)
print("P :",P)
print("Q : ",Q)

P : [[1 7]
 [2 1]
 [3 2]]
Q :  [[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [62]:
R = np.array([[1,3,1],[1,0,1]])

C3 = np.dot(P,R)
print(C3)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [63]:
#Determinant
det = np.linalg.det(C3)
print(det)
#determinant of C3=0 hence matrix is singular hence it cannot have inverse
#S2=np.linalg.inv(C3) # so it will give error

0.0


In [64]:
M = np.array([[1,-1],[2,3]])
print(np.linalg.det(M)) #so its determinant is not equal to zero,hence its inverse can be determined

print(np.linalg.inv(M))

5.000000000000001
[[ 0.6  0.2]
 [-0.4  0.2]]
