In [29]:
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [30]:
print(v+w)

[3 4 4]


In [31]:
print(v-w)

[-1 -6  0]


In [32]:
#Scalar multiplication
print(3*v)

#magnitude of Vector or the length of the vectors
print(np.linalg.norm(v))

[ 3 -3  6]
2.449489742783178


In [33]:
#Dot product which gives scalar
s = np.dot(v,w)
print(s)

1
